page_title = "US Racial Disparity Index Dashboard"
states = {
    # "All": "All",
    "AK": "Alaska",
    "AL": "Alabama",
    "AR": "Arkansas",
    "AZ": "Arizona",
    "CA": "California",
    "CO": "Colorado",
    "CT": "Connecticut",
    "DC": "District of Columbia",
    "DE": "Delaware",
    "FL": "Florida",
    "GA": "Georgia",
    "HI": "Hawaii",
    "IA": "Iowa",
    "ID": "Idaho",
    "IL": "Illinois",
    "IN": "Indiana",
    "KS": "Kansas",
    "KY": "Kentucky",
    "LA": "Louisiana",
    "MA": "Massachusetts",
    "MD": "Maryland",
    "ME": "Maine",
    "MI": "Michigan",
    "MN": "Minnesota",
    "MO": "Missouri",
    "MS": "Mississippi",
    "MT": "Montana",
    "NC": "North Carolina",
    "ND": "North Dakota",
    "NE": "Nebraska",
    "NH": "New Hampshire",
    "NJ": "New Jersey",
    "NM": "New Mexico",
    "NV": "Nevada",
    "NY": "New York",
    "OH": "Ohio",
    "OK": "Oklahoma",
    "OR": "Oregon",
    "PA": "Pennsylvania",
    "RI": "Rhode Island",
    "SC": "South Carolina",
    "SD": "South Dakota",
    "TN": "Tennessee",
    "TX": "Texas",
    "UT": "Utah",
    "VA": "Virginia",
    "VT": "Vermont",
    "WA": "Washington",
    "WI": "Wisconsin",
    "WV": "West Virginia",
    "WY": "Wyoming",
}
descriptions = {
    "header": "This site seeks to explore the relationship between individuals' socioeconomic characteristics and their likelihood of homeownership. Specifically we define a **Racial Disparity Index (RDI)** that quantifies racial inequality in an outcome gap in the homeownership problem space.",
    "map": "In this page, users can visualize how specific socioeconomic characteristics change for PUMA Areas across the US for a specific year. According to the [US Census](https://www.census.gov/programs-surveys/geography/guidance/geo-areas/pumas.html), Public Use Microdata Areas (PUMAs) are statistical regions that partition each state into areas with at least 100,000 people.",
    "timeline": "In this page, users can visualize how the Racial Disparity Index (RDI) of a particular state changes over time.",
    "model": "In this page, users can run our models with their own sample data. Please refer to the sample input file to see how to format the uploaded CSV that we will plug into our models.",
}
